name: gh-secrets-scanner
on:
  schedule:
    - cron: "0 0 * * *"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: kams-mash/gh-secrets-scanner-action@master
